{% set version = "2.0.6" %}

package:
  name: bob.ip.optflow.hornschunck
  version: {{ version }}

source:
  fn: bob.ip.optflow.hornschunck-{{ version }}.zip
  md5: 6c40bb94784249b70a47c2ff57cf809a
  url: https://pypi.python.org/packages/source/b/bob.ip.optflow.hornschunck/bob.ip.optflow.hornschunck-{{ version }}.zip

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.ip.color
    - scipy
    - pkg-config
    - boost 1.60.*

  run:
    - python
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.ip.color
    - scipy
    - boost 1.60.*

test:
  commands:
    - nosetests -sv bob.ip.optflow.hornschunck

  imports:
    - bob
    - bob.ip
    - bob.ip.optflow
    - bob.ip.optflow.hornschunck
    - bob.ip.optflow.hornschunck.example

  requires:
    - nose

about:
  home: https://github.com/bioidiap/bob.ip.optflow.hornschunck
  license: GNU General Public License v3 (GPLv3)
  summary: Python bindings to the optical flow framework of Horn & Schunck

extra:
  recipe-maintainers:
    - 183amir
