travis:
  secure:
    BINSTAR_TOKEN: h5URu/xsK0gZn2lSFLibEExJ6KUEaRDkJ4cHNPB3vxBNHe34p1l0rDBifGpSBw4vn/r+UXdT1EXtMnnvG9RJnmJsMfChYmdYSCYz09n7/dVEoAXeSd2pPCuo3XH3V2lWWP+4jwDM3IQBtMgxTN5BBzLUvDgpsnKncMpsYpNX5csGGhhjnxzkJCJ4O2u2oHFShNMDnA+X0FPui9Gs9mHUw4zgM7j9d4ZRlbeOUX6EL+guBbOw9Au5MacMj71DfkdgjBATXjucf8WldFKg0/VRc7IHUqLT8PllGzBHUxyVL8JoBr7o/j6ehh3j5nlCNG1jnFgqhCm5G3PBUfv+4oThGXlmfH1mkhJUZcdLNR1sJR8ACAxqcFXg6z7CyM8+46ngIlFbyD6plKR/XxBNCS9IM1dkeY+u+PcmVXYsCNUEpfXv38NuDj5Y1j9niSo5PJxIozZjSPBhni9w0T24Wq2aHNaQb0EG6FxLapcyXbKvum/wf7kqtp1T++v0m8pND4VnYchmOhLe9vd1J9dbU3PUiKByJFDIe4M9upORnmY77OMh1xHJnnmKGEL7cO6GepDNeTPcJ6fmWuBP4q3AH02wmBNu/1Q1VBnErHAQfjk4WbAVEf7Lp2HghmMMKP0jo6JnKFR3MIYlA0uWawIA248WpWrEJqrWWjKCvE0QNweoEd8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
